import{S as u,A as f}from"./assets/vendor-CAbnLzZU.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))a(s);new MutationObserver(s=>{for(const e of s)if(e.type==="childList")for(const o of e.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&a(o)}).observe(document,{childList:!0,subtree:!0});function n(s){const e={};return s.integrity&&(e.integrity=s.integrity),s.referrerPolicy&&(e.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?e.credentials="include":s.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function a(s){if(s.ep)return;s.ep=!0;const e=n(s);fetch(s.href,e)}})();function p(){const t={name:"",phone:"",message:""},r=document.querySelector(".contact-form"),n="data-contact-modal",a=localStorage.getItem(n);if(a){const e=JSON.parse(a);t.name=e.name||"",t.phone=e.phone||"",t.message=e.message||"",r.elements.name.value=t.name,r.elements.phone.value=t.phone,r.elements.message.value=t.message}r.addEventListener("input",e=>{const{name:o,value:d}=e.target;t[o]=d.trim(),localStorage.setItem(n,JSON.stringify(t))}),r.addEventListener("submit",e=>{e.preventDefault(),t.name===""||t.phone===""?alert("Fill please all fields"):(localStorage.removeItem(n),t.name="",t.phone="",t.message="",r.reset(),r.querySelectorAll(".modal-input").forEach(o=>{o.classList.remove("is-touched")}))}),document.querySelectorAll(".modal-input").forEach(e=>{e.addEventListener("blur",()=>{e.classList.add("is-touched")}),e.addEventListener("input",()=>{e.validity.valid&&e.classList.remove("is-touched")})})}const m="https://deserts-store.b.goit.study/api/feedbacks?limit=10&page=1";let c=null;function v(){c||(c=new u(".feedback-swiper",{slidesPerView:1,spaceBetween:20,grabCursor:!0,observer:!0,observeParents:!0,navigation:{prevEl:".swiper-btn-prev",nextEl:".swiper-btn-next"},pagination:{el:".feedback-pagination",clickable:!0},breakpoints:{768:{slidesPerView:3,spaceBetween:24},1440:{slidesPerView:3,spaceBetween:24}}}))}async function i(){const t=document.getElementById("feedback-container");if(!t){setTimeout(i,100);return}try{const r=await fetch(m);if(!r.ok)throw new Error("Помилка сервера");const n=await r.json(),a=Array.isArray(n)?n:n.feedbacks||n.results||n.data||[];if(a.length===0){t.innerHTML='<div class="swiper-slide">Відгуків поки немає...</div>';return}g(a.slice(0,10),t)}catch(r){console.error("Помилка при завантаженні API:",r),t.innerHTML='<div class="swiper-slide">Не вдалося завантажити відгуки...</div>'}}function g(t,r){r.innerHTML="",t.forEach(n=>{const s=`
      <div class="swiper-slide">
        <div class="feedback-card">
          <div class="card-top-content">
            <div class="rating-stars" style="--rating-percent: ${(n.rate||5)/5*100}%" title="Рейтинг: ${n.rate||5}"></div>
            <p class="feedback-text">${n.description||"Чудовий десерт!"}</p>
          </div>
          <p class="feedback-user">${n.author||"Анонімний клієнт"}</p>
        </div>
      </div>
    `;r.insertAdjacentHTML("beforeend",s)}),v()}document.readyState==="loading"?document.addEventListener("DOMContentLoaded",i):i();const l=document.querySelector(".js-faq-accordion");l&&new f(l,{duration:300,collapse:!0,showMultiple:!1});p();
//# sourceMappingURL=index.js.map
